name: publish
on:
  release:
    types: [published]
    branches:
      - master # Default release branch
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
          
      - name: install packages
        run: dotnet restore
          
      - name: build
        run: dotnet build

      - name: test
        run: dotnet test
        
      - name: publish Byndyusoft.Logging.OpenTracing
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Byndyusoft.Logging.OpenTracing/Byndyusoft.Logging.OpenTracing.csproj
          VERSION_FILE_PATH: Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
     
      - name: publish Byndyusoft.Logging.OpenTelemetry
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Byndyusoft.Logging.OpenTelemetry/Byndyusoft.Logging.OpenTelemetry.csproj
          VERSION_FILE_PATH: Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true

     
      - name: publish Byndyusoft.Logging
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Byndyusoft.Logging/Byndyusoft.Logging.csproj
          VERSION_FILE_PATH: Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
